language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"

before_script:
  - cp src/app/private.config.template.ts src/app/private.config.ts

jobs:
  include:
    - stage: lint
      script: ng lint
    - stage: test
      script: npm test
